# Workflow configuration for DataDog RCA Tool
# This workflow demonstrates how to use the DataDog RCA tool for root cause analysis

# Define the functions (tools) that will be available
functions:
  # DataDog RCA tool
  datadog_analyzer:
    _type: datadog_rca  # This should match the name in DataDogRCAConfig
    base_url: "https://sre-api-service-ext.bestegg.com"  # Default URL, can be overridden
    default_scenario_id: "11111111-1111-1111-1111-111111111111"  # Default scenario ID
    default_env: "prod"
    window_minutes: 30
  
  # Optional: Keep other tools as needed
  slack_convo_viewer:
    _type: slack_convo_viewer
    base_url: "https://sre-api-service-ext.bestegg.com"
    reset_scenarios: false

# Configure the LLM to be used
llms:
  # Using NIM (NVIDIA Inference Microservice) with a powerful model
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct  # Using a powerful model for better understanding
    temperature: 0.2  # Slight randomness for more natural responses

# Define the workflow
workflow:
  # Use a ReAct agent that can reason and use tools
  _type: react_agent
  
  # List all available tools
  tool_names: 
    - datadog_analyzer
    - slack_convo_viewer  # Optional: include other tools as needed
  
  # Specify which LLM to use
  llm_name: nim_llm
  
  # Enable verbose output to see the agent's reasoning process
  verbose: true
  
  # Set the maximum number of retries for the agent
  parse_agent_response_max_retries: 3
  
  # Optional: System message to guide the agent's behavior
  system_message: |
    You are a helpful assistant that can analyze system metrics and logs using DataDog and Slack and you MUST state the information you are using from DataDog and Slack.
    When asked about system performance, errors, or root cause analysis, use the datadog_analyzer tool and the slack_convo_viewer tool.
    Focus on providing the most relevant information and insights, and explain how they relate to DataDog and Slack. 
    Sound confident with all of your claims and provide further steps to resolve the issue.
    NEVER SAY THAT YOU DON'T KNOW SOMETHING. ALWAYS MAKE YOUR BEST GUESS.
